/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.friday.GazeboIndustries.com.br;

import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import static javax.swing.JFrame.EXIT_ON_CLOSE;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gazebo
 */
public class Interface extends javax.swing.JFrame {
      JPanel painelFundo;
      DataBaseConnection connection = new DataBaseConnection();
      JTable tabela;
      JScrollPane barraRolagem;
      DefaultTableModel val = new DefaultTableModel();
      String LastResponse = "null";
      ImageIcon icon;
      
     
    /**
     * Creates new form Interface
     */
    public Interface() {
       
         
         painelFundo = new JPanel();
         painelFundo.setLayout(new GridLayout(1, 1));

         tabela = new JTable(val);
        
         barraRolagem = new JScrollPane(tabela);
         painelFundo.add(barraRolagem); 

         getContentPane().add(painelFundo);
         setDefaultCloseOperation(EXIT_ON_CLOSE);
         painelFundo.setSize(900, 720);
         painelFundo.setVisible(false);
        
        initComponents();
        setLocationRelativeTo(null);  

         /*ImageIcon icon = new ImageIcon("C:\\Users\\Gazebo\\Pictures\\IF.png");
         Imagem.setIcon(icon);
        */

         painelFundo.setLocation(320,  120);
         Imagem.setVisible(false);
         
         Timer timer = new Timer(1000, new Clock());
        timer.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        Imagem = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblDayOfWeek = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sexta-Feira Interface");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1680, 925));
        getContentPane().setLayout(null);

        lblDate.setFont(new java.awt.Font("Wide Latin", 3, 24)); // NOI18N
        lblDate.setForeground(new java.awt.Color(0, 102, 204));
        lblDate.setText("20/20/20");
        getContentPane().add(lblDate);
        lblDate.setBounds(1240, 30, 300, 90);
        getContentPane().add(Imagem);
        Imagem.setBounds(270, 110, 1020, 780);

        lblTime.setFont(new java.awt.Font("Wide Latin", 3, 48)); // NOI18N
        lblTime.setForeground(new java.awt.Color(0, 102, 204));
        lblTime.setText("20:10");
        getContentPane().add(lblTime);
        lblTime.setBounds(1340, 170, 300, 90);

        lblDayOfWeek.setFont(new java.awt.Font("Wide Latin", 3, 24)); // NOI18N
        lblDayOfWeek.setForeground(new java.awt.Color(0, 102, 204));
        lblDayOfWeek.setText("6º Feira");
        getContentPane().add(lblDayOfWeek);
        lblDayOfWeek.setBounds(510, 30, 250, 80);

        Background.setIcon(new javax.swing.ImageIcon("E:\\Sexta-Feira(A.I.)-Mark 5\\Sexta-Feira_Images\\BackgroundFriday.png")); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 1680, 920);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Imagem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDayOfWeek;
    private javax.swing.JLabel lblTime;
    // End of variables declaration//GEN-END:variables

  class Clock implements ActionListener{

    @Override
    public void actionPerformed(ActionEvent e) {
        SetClock();
        String[] DataBase = connection.getInteration();
        String response = DataBase[1];
        
        //response.equals("TESTE") && !response.equals(LastResponse) && !LastResponse.equals("null")
        
       if(!response.equals(LastResponse) && !LastResponse.equals("null") ){
            switch(Integer.parseInt(response)){
                case 0:
                    painelFundo.setVisible(false);
                    Imagem.setVisible(false);
                    break;
                case 1:
                    SetTable(connection.getProjects(), connection.getHeadProjects());
                    break;
                    
               case 2:
                    SetTable(connection.getReminder(), connection.getHeadReminder());
                    break;
                    
               case 3:
                    SetTable(connection.getHomeWorks(), connection.getHeadHomeWork());
                    break;
            
               case 4:
                   icon = new ImageIcon("E:\\Sexta-Feira(A.I.)-Mark 5\\Sexta-Feira_Images\\Tabela Periódica.jpg");
                   Imagem.setIcon(icon);
                   Imagem.setVisible(true);
                    break;
            
               case 5:
                   icon = new ImageIcon("E:\\Sexta-Feira(A.I.)-Mark 5\\Sexta-Feira_Images\\Mapa Mundi.jpg");
                   Imagem.setIcon(icon);
                   Imagem.setVisible(true);
                    break;
                    
               case 6:
                   icon = new ImageIcon("E:\\Sexta-Feira(A.I.)-Mark 5\\Sexta-Feira_Images\\Mapa Mundi vegetação.jpg");
                   Imagem.setIcon(icon);
                   Imagem.setVisible(true);
                    break;
                    
                case 7:
                   icon = new ImageIcon("E:\\Sexta-Feira(A.I.)-Mark 5\\Sexta-Feira_Images\\Brasil Político.jpg");
                   Imagem.setIcon(icon);
                   Imagem.setVisible(true);
                    break;
                
                case 8:
                   icon = new ImageIcon("E:\\Sexta-Feira(A.I.)-Mark 5\\Sexta-Feira_Images\\diagrama-de-pauling.jpg");
                   Imagem.setIcon(icon);
                   Imagem.setVisible(true);
                    break;
                    
                 case 9:
                   icon = new ImageIcon("E:\\Sexta-Feira(A.I.)-Mark 5\\Sexta-Feira_Images\\Equações Dinamica.png");
                   Imagem.setIcon(icon);
                   Imagem.setVisible(true);
                    break;
             
                 case 10:
                   icon = new ImageIcon("E:\\Sexta-Feira(A.I.)-Mark 5\\Sexta-Feira_Images\\TabelaSenoCossenoTangente.png");
                   Imagem.setIcon(icon);
                   Imagem.setVisible(true);
                    break;
                    
            }
           
        }
        LastResponse = response;
    } 
   }
  
  public void SetClock(){
      try {
            Locale locale = new Locale("pt","BR");
            GregorianCalendar calendar = new GregorianCalendar();
            SimpleDateFormat formatadorData= new SimpleDateFormat("dd'/'MM'/'yyyy",locale);
            SimpleDateFormat formatadorHora = new SimpleDateFormat("HH':'mm",locale);

            Calendar cal = Calendar.getInstance();

            String Date = formatadorData.format(calendar.getTime());
            String Time = formatadorHora.format(calendar.getTime());

             cal.setTime(formatadorData.parse(Date));
             String DayOfWeek = Integer.toString(cal.get(Calendar.DAY_OF_WEEK)) + "º Feira";

             if(DayOfWeek.equals("7º Feira")){
                 DayOfWeek = "Sábado";
                 
             }else{
                 if(DayOfWeek.equals("1º Feira")){
                     DayOfWeek = "Domingo";
                 }
             }        
             
             lblDayOfWeek.setText(DayOfWeek);
             lblDate.setText(Date);
             lblTime.setText(Time);
             
            
         
         } catch (ParseException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }

  }
  
  public void SetTable(Object dados[][], String colunas[]){
      try{
      
            DefaultTableModel TableModel = (DefaultTableModel) tabela.getModel();
            
            
            while(TableModel.getRowCount() > 0){
                TableModel.removeRow(0);
            }
 
            TableModel.setColumnIdentifiers(colunas);
         

            for(int i = 0; i<dados.length; i++){
                
                TableModel.addRow(dados[i]);
            }
          
            painelFundo.setVisible(true);
            
            
            /*painelFundo = new JPanel();
            painelFundo.setLayout(new GridLayout(1, 1));
            tabela = new JTable(dados, colunas);
            JScrollPane barraRolagem = new JScrollPane(tabela);
            painelFundo.add(barraRolagem); 

            getContentPane().add(painelFundo);
            setDefaultCloseOperation(EXIT_ON_CLOSE);
            painelFundo.setSize(600, 520);
            painelFundo.setVisible(true);

            painelFundo.setLocation(320,  120);*/

            remove(Background);

            ImageIcon icon = new ImageIcon("E:\\Sexta-Feira(A.I.)-Mark 5\\Sexta-Feira_Images\\BackgroundFriday.png");

            JPanel painel = new JPanel();

            JLabel Background = new JLabel();
            Background.setIcon(icon);

            painel.add(Background);

            getContentPane().add(painel);
            painel.setSize(1680, 920);
            painel.setVisible(true);
            painel.setLocation(0, -5);
        
      }catch(Exception e){
          System.out.println(e);
        }
      }
  }
 
